apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpdesk.fullname" . }}-backend-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.database }}"
