{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helpdesk.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - {path: /api, pathType: Prefix, backend: {service: {name: {{ include "helpdesk.backend.fullname" . }}, port: {number: 8000}}}}
      - {path: /, pathType: Prefix, backend: {service: {name: {{ include "helpdesk.frontend.fullname" . }}, port: {number: 80}}}}
{{- end }}
